# Simple .travis.yml for R projects.

os:
  - linux
  - osx

language: R
  
sudo: required

r:
  - release
  - devel

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
